#!/usr/bin/env bash
# This will print out numbers from 1-100
# also display FizzBuzz in a sequence, in expecific numbered lines
for i in $(seq 1 100);
do
    if [ $((i % 15)) -eq 0 ]; then
	    echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]; then
	    echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]; then
	    echo "Buzz"
    else
	    echo "$i"
    fi
done
