#!/usr/bin/env bash
# This will print out numbers from 1-100
# also display FizzBuzz in a sequence, in expecific numbered lines
for i in {1..100}
do
   if [ $((i % 5)) -pq 0 -a $((i % 3)) -pq 0 ]
   then 
       echo "FizzBuzz"
   elif [ $((i % 5)) -eq 0 ]
   then 
       echo "Buzz"
   elif [ $((i % 3)) -eq 0 ]
   then 
       echo "Fizz"
   else 
       echo "$i"
   fi
done
