#!/usr/bin/env bash
# This will only print out the following from the file /etc/passwd
# username, user id and home directory path for the user
while read line; do
    echo "$line" | cut -d':' -f 1,3,6
done < /etc/passwd
