#!/usr/bin/env bash
# This will print "Best School" 10 times but in the 9th line will say 'hi'
x=1
while [ $x -le 10 ]
do
   echo "Best School"
   if [ $x -eq 9 ]
   then 
       echo "Hi"
   fi
   ((x++))
done
