#!/usr/bin/env bash
# Print from 1-10 but in the 4th line 'bad luck', 8th 'good luck', and 'Best School' in the rest
x=1
while [ $x -le 10 ]
do
      if [ $x -eq 4 ]
      then
          echo "bad luck"
      elif [ $x -eq 8 ]
      then 
          echo "good luck"
      else
          echo "Best School"
      fi
      ((x++))
done
