#!/usr/bin/env bash
# Checks if file exists and prints whether it does or not
# also checks if the files are empty and prints wheter it is or not
FILE="school"
if [ -e $FILE ]
then
    echo "$FILE file exists"

    if [ -s $FILE ]
    then
        echo "$FILE file is not empty"
    else
        echo "$FILE file is empty"
    fi
   
    if [ -f $FILE ]
    then 
        echo "$FILE file is a regular file"
    fi
else
    echo "$FILE file does not exist"
fi
