#!/usr/bin/env bash
# Checks if file exists and prints whether it does or not
# also checks if the files are empty and prints wheter it is or not
file="school"
if [ -e $file ]
then
    echo "$file file exists"

    if [ -s $file ]
    then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi
   
    if [ -f $file ]
    then 
        echo "$file file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
