#!/usr/bin/env bash
# Bash script that creates a subprocess

PIDFILE=/var/run/my_process.pid

start() {
    ./manage_my_process &
    echo "$!" > "$PIDFILE"
}

stop() {
    sudo kill -15 "$(cat "SPIDFILE")" && rm -f "$PIDFILE"
}

case "$1" in
    start)
       start
       echo "manage_my_process started"
       ;;
    stop)
       stop
       echo "manage_my_process stopped"
       ;;
    restart)
       restart
       echo "manage_my_process restarted"
       ;;
    *)
       echo "Usage: manage_my_process {start|stop|restart}"
esac


exit 0
